# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mafia.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmafia.proto\"\x07\n\x05\x45mpty\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\".\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0f\n\x07session\x18\x02 \x01(\x05\".\n\rUpdateRequest\x12\x0f\n\x07session\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\"\x1e\n\x0bUpdateReply\x12\x0f\n\x07message\x18\x01 \x01(\t\">\n\x0bKillRequest\x12\x0f\n\x07session\x18\x01 \x01(\x05\x12\x0e\n\x06sender\x18\x02 \x01(\t\x12\x0e\n\x06victim\x18\x03 \x01(\x05\"K\n\x0b\x43hatRequest\x12\x0f\n\x07session\x18\x01 \x01(\x05\x12\x0e\n\x06sender\x18\x02 \x01(\t\x12\r\n\x05topic\x18\x03 \x01(\t\x12\x0c\n\x04text\x18\x04 \x01(\t2\xd2\x02\n\x05Mafia\x12(\n\x08SayHello\x12\r.HelloRequest\x1a\x0b.HelloReply\"\x00\x12/\n\x0bSendUpdates\x12\x0e.UpdateRequest\x1a\x0c.UpdateReply\"\x00\x30\x01\x12\"\n\x06\x45ndDay\x12\x0e.UpdateRequest\x1a\x06.Empty\"\x00\x12$\n\nKillPlayer\x12\x0c.KillRequest\x1a\x06.Empty\"\x00\x12+\n\x0b\x43heckPlayer\x12\x0c.KillRequest\x1a\x0c.UpdateReply\"\x00\x12(\n\x0cRevealPlayer\x12\x0e.UpdateRequest\x1a\x06.Empty\"\x00\x12\'\n\rExecutePlayer\x12\x0c.KillRequest\x1a\x06.Empty\"\x00\x12$\n\nSendToChat\x12\x0c.ChatRequest\x1a\x06.Empty\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mafia_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTY._serialized_start=15
  _EMPTY._serialized_end=22
  _HELLOREQUEST._serialized_start=24
  _HELLOREQUEST._serialized_end=52
  _HELLOREPLY._serialized_start=54
  _HELLOREPLY._serialized_end=100
  _UPDATEREQUEST._serialized_start=102
  _UPDATEREQUEST._serialized_end=148
  _UPDATEREPLY._serialized_start=150
  _UPDATEREPLY._serialized_end=180
  _KILLREQUEST._serialized_start=182
  _KILLREQUEST._serialized_end=244
  _CHATREQUEST._serialized_start=246
  _CHATREQUEST._serialized_end=321
  _MAFIA._serialized_start=324
  _MAFIA._serialized_end=662
# @@protoc_insertion_point(module_scope)
